### ISSUE TITLE
Unexpected character error

### ISSUE THREAD

**Issue by Sora1995** [roxaskeyheart/Chromatics#43]
Hello! I recently was using Chromatics just fine, but after updating and tinkering around with Chromatics, it suddenly will not attach to XIV. It keeps mentioning a D drive, but I do not have one.
![chromatics](https://user-images.githubusercontent.com/1421545/27998109-091d85c6-64cc-11e7-93a4-8628e52f7782.png)

It just keeps repeating that message.

**Comment by HCrescent** [comment]
Im having the same issue.

**Comment by decoylad** [comment]
Just tried for the first time today and received this error as well.  attaching in plain text just in case easier to read that way:

`Attempting Attach..
Error: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
Internal Error:    at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at FFXIVAPP.Memory.Helpers.APIHelper.APIResponseToClass[T](String file, String uri) in D:\Downloads\ffxivapp-memory-master (4)\ffxivapp-memory-master\FFXIVAPP.Memory\Helpers\APIHelper.cs:line 142
   at FFXIVAPP.Memory.Helpers.APIHelper.GetStructures(ProcessModel processModel, String patchVersion) in D:\Downloads\ffxivapp-memory-master (4)\ffxivapp-memory-master\FFXIVAPP.Memory\Helpers\APIHelper.cs:line 85
   at FFXIVAPP.Memory.MemoryHandler.SetStructures(ProcessModel processModel, String patchVersion) in D:\Downloads\ffxivapp-memory-master (4)\ffxivapp-memory-master\FFXIVAPP.Memory\MemoryHandler.cs:line 95
   at FFXIVAPP.Memory.MemoryHandler.SetProcess(ProcessModel processModel, String gameLanguage, String patchVersion, Boolean ignoreJSONCache) in D:\Downloads\ffxivapp-memory-master (4)\ffxivapp-memory-master\FFXIVAPP.Memory\MemoryHandler.cs:line 83
   at Chromatics.Chromatics.InitiateMemory()
`

**Comment by logicallysynced** [comment]
~~The webserver where some config data files are downloaded from is currently down for maintenance and that is affecting Chromatics currently.~~

I need to implement a mirror system for those files in this case.

~~In the mean time if you have been able to use Chromatics before, turning on the "Use Local cache" checkbox under settings and restarting Chromatics may help. For new installers I will get back to you ASAP when I know more information.~~

This should be fixed now. Please restart Chromatics with "Use Local Cache" unchecked!
