### ISSUE TITLE
Attach broken.

### ISSUE THREAD

**Issue by MadHalaster** [roxaskeyheart/Chromatics#48]
The past few days the app has not been able to attach to FFXIV for me at all.
Chromatics 2.2.7 Beta
FFXIV 2017.08.03.0000.0000 (2709518, ex1:2017.06.01.0000.0001)

As soon as FFXIV is launched it starts spewing out the following error message repeatedly until the game is closed. 

```
Attempting Attach..
Error: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
Internal Error:    at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Sharlayan.Helpers.APIHelper.APIResponseToClass[T](String file, String uri) in D:\Users\Icehunter\Documents\GitHub\sharlayan\Sharlayan\Helpers\APIHelper.cs:line 141
   at Sharlayan.Helpers.APIHelper.GetStructures(ProcessModel processModel, String patchVersion) in D:\Users\Icehunter\Documents\GitHub\sharlayan\Sharlayan\Helpers\APIHelper.cs:line 80
   at Sharlayan.MemoryHandler.SetProcess(ProcessModel processModel, String gameLanguage, String patchVersion, Boolean ignoreJSONCache, Boolean scanAllMemoryRegions) in D:\Users\Icehunter\Documents\GitHub\sharlayan\Sharlayan\MemoryHandler.cs:line 88
   at Chromatics.Chromatics.InitiateMemory()
```

**Comment by danielrouleau** [comment]
It looks like xivapp.com is down for maintenance, which is used for reading memory signatures internally to parse the data. If you have successfully run Chromatics recently, you can go into settings and toggle "Use Local Cache" in the meantime.

**Comment by MadHalaster** [comment]
Ahhh, thanks for the comment. Unfortunately when I encountered the problem I fully uninstalled the app and wiped out all the data to try to fix the issue with a reinstall. If this occurs again in the future I will know what to try. :)

**Comment by MadHalaster** [comment]
Closing this as addressed.
