### ISSUE TITLE
Log errors, no lights

### ISSUE THREAD

**Issue by arlarzelere3** [roxaskeyheart/Chromatics#5]
Below is the log entry this is repeated in the log over and over.

Version 1.1.3
Logitech G13 and G600

****\* 2015-12-08T20:06:39 - BeforeLogLineRead event
11|2015-12-08T20:06:34.4110000-05:00|1|10044098
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Chromatics.Chromatics.oFormActMain_BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
   at Advanced_Combat_Tracker.LogLineEventDelegate.Invoke(Boolean isImport, LogLineEventArgs logInfo)
   at Advanced_Combat_Tracker.FormActMain.ParseRawLogLine(Boolean isImport, DateTime ParsedLogTime, String LogLine)
   at Advanced_Combat_Tracker.FormActMain.WriteExceptionLog(Exception ex, String MoreInfo)
   at Advanced_Combat_Tracker.FormActMain.ParseRawLogLine(Boolean isImport, DateTime ParsedLogTime, String LogLine)
   at Advanced_Combat_Tracker.FormActMain.ReadLog()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by logicallysynced** [comment]
Are you running Logitech Gaming Software before running ACT and is the "Allow games to control illumination" checkbox selected in the Logitech Gaming Software settings?

**Comment by arlarzelere3** [comment]
Yup, LGS 8.75.30 is running, and allows games to control illumination.

**Comment by logicallysynced** [comment]
My version of LGS is 8.76.155 - Can you try updating it and see if this resolves the problem?

If this does not resolve the issue, can you send me a screenshot of your ACT plugins tab as well as the Chromatics tab. Also please let me know the following to help further diagnose the problem:
- Operating System
- System Architecture (x64, x86, etc)
