### ISSUE TITLE
breaks lighting on Blackwidow X Chroma

### ISSUE THREAD

**Issue by coollambda** [roxaskeyheart/Chromatics#63]
Hello, just today installed this and when I run Chromatics, the lighting freezes on my Razer Blackwidow X Chroma (I have it on wave) and the lighting controls in Synapse do nothing until I close Chromatics. Once I close Chromatics, the lighting continues just fine. Launching Chromatics before or during FFXIV makes no difference, the lighting just freezes and nothing else happens. I do start Chromatics with admin privileges. Also, seems like Chromatics isn't saving settings. No matter what I change in Devices tab or Settings tab, the default settings are back every time I start Chromatics.

Windows 10 Home - Version 1709
Chromatic 2.3.1 Beta
Logitech Gaming Software 8.96.88 (for my headset)
Razer Synapse 3.3.123.385 (for my keyboard)
.Net Framework 4.6, and VS 2015 and 2017 runtimes installed
Windows Defender is the only antivirus currently in use

I get the following unhandled exception message when starting Chromatics

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.DllNotFoundException: Unable to load DLL 'x64\LogitechLcdEnginesWrapper.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Logitech_LCD.NativeMethods.Init(String friendlyName, LcdType lcdType)
   at Logitech_LCD.LogitechLcd.Init(String friendlyName, LcdType lcdType)
   at Chromatics.LCDInterfaces.LogitechLcd.InitializeLcd() in D:\Git\Chromatics\Chromatics\Chromatics\LCDInterfaces\LogitechLCD.cs:line 196
   at Chromatics.LCDInterfaces.LogitechLcdInterface.InitializeLcdSdk() in D:\Git\Chromatics\Chromatics\Chromatics\LCDInterfaces\LogitechLCD.cs:line 36
   at Chromatics.Chromatics.MainThread() in D:\Git\Chromatics\Chromatics\Chromatics\Chromatics.cs:line 462
   at Chromatics.Chromatics.OnLoad(EventArgs e) in D:\Git\Chromatics\Chromatics\Chromatics\Chromatics.cs:line 226
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Chromatics
    Assembly Version: 2.3.1.0
    Win32 Version: 2.3.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/Chromatics.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.Practices.ServiceLocation
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/Microsoft.Practices.ServiceLocation.DLL
----------------------------------------
GalaSoft.MvvmLight.Extras
    Assembly Version: 5.3.0.19032
    Win32 Version: 5.3.0.19032
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/GalaSoft.MvvmLight.Extras.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.ComponentModel.dll
----------------------------------------
System.Collections
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll
----------------------------------------
System.Reflection
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Reflection/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.dll
----------------------------------------
System.Threading
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Threading/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.dll
----------------------------------------
System.Globalization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Globalization/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Globalization.dll
----------------------------------------
System.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Linq/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Linq.dll
----------------------------------------
Sharlayan
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/Sharlayan.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Cyotek.Windows.Forms.ColorPicker
    Assembly Version: 1.0.0.0
    Win32 Version: 1.7.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/Cyotek.Windows.Forms.ColorPicker.DLL
----------------------------------------
LifxNet
    Assembly Version: 2.1.1.0
    Win32 Version: 2.1.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/LifxNet.DLL
----------------------------------------
Q42.HueApi
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/Q42.HueApi.DLL
----------------------------------------
Gma.System.MouseKeyHook
    Assembly Version: 5.4.0.0
    Win32 Version: 5.4.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/Gma.System.MouseKeyHook.DLL
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Corale.Colore
    Assembly Version: 5.2.0.0
    Win32 Version: 5.2.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/Corale.Colore.DLL
----------------------------------------
Corale.Colore.WinForms
    Assembly Version: 5.2.0.0
    Win32 Version: 5.2.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/Corale.Colore.WinForms.DLL
----------------------------------------
CUE.NET
    Assembly Version: 1.1.3.1
    Win32 Version: 1.1.3.1
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/CUE.NET.DLL
----------------------------------------
System.Threading.Tasks
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Threading.Tasks/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.Tasks.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Primitives/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Primitives.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 4.1.1.0
    Win32 Version: 4.6.24705.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.Net.Sockets.DLL
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Extensions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Extensions.dll
----------------------------------------
System.Text.Encoding
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Text.Encoding/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Text.Encoding.dll
----------------------------------------
System.IO
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.IO.dll
----------------------------------------
Logitech-LCD
    Assembly Version: 1.0.4.0
    Win32 Version: 1.0.4.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/Logitech-LCD.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

And this is the debug window
```
Starting Chromatics Version 2.3.1 (Beta)
Searching for devices.chromatics..
Attempting to load devices.chromatics..
Error loading devices.chromatics. Error: Object reference not set to an instance of an object.
Searching for settings.chromatics..
Attempting to load settings.chromatics..
settings.chromatics loaded.
Searching for mappings.chromatics..
Attempting to load mappings.chromatics..
mappings.chromatics loaded.
Updated Chromatics Updater to latest version.
Attempting to load Razer SDK..
Razer SDK Loaded (2.9.2)
Attempting to load Logitech SDK..
Logitech SDK Loaded
Attempting to load CUE SDK..
CUE SDK failed to load. EX: Error in the application.
CUE SDK failed to load.
Attempting to load Coolermaster SDK..
Unable to find any valid Coolermaster devices.
Coolermaster SDK failed to load.
Attempting to load LIFX SDK..
LIFX SDK Loaded
Logitech Conflict Mode Enabled.
No new updates currently available.
```

EDIT: I forgot to mention, the relative path "x64\LogitechLcdEnginesWrapper.dll" does exist

**Comment by logicallysynced** [comment]
If you have Logitech’s LGS software installed, try exiting it before running Chromatics. Also make sure Logitech LCD devices are disabled (unchecked) in the Devices tab of the Chromatics window.

**Comment by logicallysynced** [comment]
Correction: “Enable LCD displays” is under the settings tab.

**Comment by coollambda** [comment]
Exiting LGS before running Chromatics worked! Thanks!
