### ISSUE TITLE
Chromatics experiences an unhandled exception when changing focus from ACT Web Server URL under ARX

### ISSUE THREAD

**Issue by didyouexpectthat** [roxaskeyheart/Chromatics#96]
I was playing around with Chromatics 2.4.6 and dropped down the menu in ARX Template to view options and received the following error. It happens after changing focus from ACT Web Server URL to ARX Template dropdown. Windows 10
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Chromatics.Chromatics.txt_arx_actip_TextChanged(Object sender, EventArgs e) in C:\Users\Dani\Source\Repos\roxaskeyheart\Chromatics\Chromatics\Controllers\GUIController.cs:line 1626
   at System.Windows.Forms.Control.OnValidated(EventArgs e)
   at System.Windows.Forms.Control.PerformControlValidation(Boolean bulkValidation)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Chromatics
    Assembly Version: 2.4.6.0
    Win32 Version: 2.4.6.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/Chromatics.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3314.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
CommonServiceLocator
    Assembly Version: 2.0.2.0
    Win32 Version: 2.0.2.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/CommonServiceLocator.DLL
----------------------------------------
GalaSoft.MvvmLight.Extras
    Assembly Version: 5.4.1.0
    Win32 Version: 5.4.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/GalaSoft.MvvmLight.Extras.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.1.2.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.Runtime.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.7.3190.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 4.0.1.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.ComponentModel.DLL
----------------------------------------
System.Threading
    Assembly Version: 4.0.11.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.Threading.DLL
----------------------------------------
System.Collections
    Assembly Version: 4.0.11.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.Collections.DLL
----------------------------------------
System.Reflection
    Assembly Version: 4.1.2.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.Reflection.DLL
----------------------------------------
System.Globalization
    Assembly Version: 4.0.11.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.Globalization.DLL
----------------------------------------
System.Linq
    Assembly Version: 4.1.2.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.Linq.DLL
----------------------------------------
Sharlayan
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/Sharlayan.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Cyotek.Windows.Forms.ColorPicker
    Assembly Version: 1.0.0.0
    Win32 Version: 1.7.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/Cyotek.Windows.Forms.ColorPicker.DLL
----------------------------------------
LifxNet
    Assembly Version: 2.1.1.0
    Win32 Version: 2.1.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/LifxNet.DLL
----------------------------------------
Q42.HueApi
    Assembly Version: 3.6.2.0
    Win32 Version: 3.6.2.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/Q42.HueApi.DLL
----------------------------------------
Gma.System.MouseKeyHook
    Assembly Version: 5.6.130.0
    Win32 Version: 5.6.130.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/Gma.System.MouseKeyHook.DLL
----------------------------------------
CSharpAnalytics.Net45
    Assembly Version: 1.2.0.0
    Win32 Version: 1.2.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/CSharpAnalytics.Net45.DLL
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.2.0.0
    Win32 Version: 4.6.26011.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.Net.Http.DLL
----------------------------------------
Colore
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/Colore.DLL
----------------------------------------
Wooting.NET
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/Wooting.NET.DLL
----------------------------------------
System.Threading.Tasks
    Assembly Version: 4.0.11.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.Threading.Tasks.DLL
----------------------------------------
System.Net.Primitives
    Assembly Version: 4.0.11.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.Net.Primitives.DLL
----------------------------------------
System.Net.Sockets
    Assembly Version: 4.2.0.0
    Win32 Version: 4.6.26011.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.Net.Sockets.DLL
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 4.1.2.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.Runtime.Extensions.DLL
----------------------------------------
System.Text.Encoding
    Assembly Version: 4.0.11.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.Text.Encoding.DLL
----------------------------------------
System.IO
    Assembly Version: 4.1.2.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.IO.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.



```

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
